/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author krishajoshi
 */

public class Flights extends javax.swing.JFrame {

    /**
     * Creates new form Flights
     */
    
    
    public Flights() {
        initComponents();
        displayFlights();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TakeOffDate = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FSource = new javax.swing.JComboBox<>();
        FDestination = new javax.swing.JComboBox<>();
        FCode = new javax.swing.JTextField();
        NoOfSeats = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightsTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 64, 128));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amsmini/Airplane Take Off.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel10)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addGap(53, 53, 53)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 940));

        TakeOffDate.setBackground(new java.awt.Color(170, 201, 246));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Flight Source");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Flight Destination");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("TakeOff Date");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Flight Code");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("Number of seats");

        FSource.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        FSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Ahmedabad", "Bangalore", "Bhopal", "Chennai", "Coimbatore", "Delhi", "Goa", "Hyderabad", "Indore", "Jaipur", "Kochi", "Lucknow", "Madurai", "Mumbai", "Nagpur", "Pune", "Surat", "Varanasi" }));

        FDestination.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        FDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Ahmedabad", "Bangalore", "Bhopal", "Chennai", "Coimbatore", "Delhi", "Goa", "Hyderabad", "Indore", "Jaipur", "Kochi", "Lucknow", "Madurai", "Mumbai", "Nagpur", "Pune", "Surat", "Varanasi" }));

        FCode.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        FCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCodeActionPerformed(evt);
            }
        });

        NoOfSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel11.setText("MANAGE FLIGHTS");

        FlightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FlightsTable.setRowHeight(40);
        FlightsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(FlightsTable);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel12.setText("Flights List");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout TakeOffDateLayout = new javax.swing.GroupLayout(TakeOffDate);
        TakeOffDate.setLayout(TakeOffDateLayout);
        TakeOffDateLayout.setHorizontalGroup(
            TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeOffDateLayout.createSequentialGroup()
                .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TakeOffDateLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(58, 58, 58)
                        .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FDestination, 0, 337, Short.MAX_VALUE)
                            .addComponent(FSource, 0, 337, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(FCode, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(NoOfSeats)))
                    .addGroup(TakeOffDateLayout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jLabel11))
                    .addGroup(TakeOffDateLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel12))
                    .addGroup(TakeOffDateLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        TakeOffDateLayout.setVerticalGroup(
            TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeOffDateLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(37, 37, 37)
                .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FSource, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(FDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TakeOffDateLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TakeOffDateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FCode, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(TakeOffDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        getContentPane().add(TakeOffDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1360, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void clear()
    {
        FCode.setText("");
        NoOfSeats.setText("");
        FSource.setSelectedIndex(0);
        FDestination.setSelectedIndex(0);   
    }
    
    private void displayFlights()
    {
        try
        {
            String url = "jdbc:mysql://localhost:3306/ams";
            String username = "root";
            String password = "Kirtan123@789"; 
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con = DriverManager.getConnection(url, username, password);
            
            Statement st = con.createStatement();
            
            String query = "Select * from manageflights";
            
            ResultSet rs = st.executeQuery(query);
            
            FlightsTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error displaying the flights!");
        }
    }
    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/ams";
        String username = "root";
        String password = "Kirtan123@789";               
        
        String fcode = FCode.getText();
        int no_of_seats = Integer.valueOf(NoOfSeats.getText());
        String fsource = FSource.getSelectedItem().toString();
        String fdestination = FDestination.getSelectedItem().toString();
        String take_off_date = date.getDate().toString();
        
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con = DriverManager.getConnection(url, username, password);
            
            String query = "INSERT into manageflights values (?,?,?,?,?)";
            
            PreparedStatement add = con.prepareStatement(query);
            
            add.setString(1, fcode);
            add.setInt(2, no_of_seats);
            add.setString(3,fsource);
            add.setString(4, fdestination);
            add.setString(5, take_off_date);
            
            int count = add.executeUpdate();
            
            if (count == 1)
            {
                JOptionPane.showMessageDialog(this,"Flight details has been saved successfully!!");
            }  
            else
            {
                JOptionPane.showMessageDialog(this,"Error saving the flight details");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error connecting to database");
        }
        displayFlights();
        clear();
    }//GEN-LAST:event_saveActionPerformed

    private void FCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCodeActionPerformed
      
    String flightCode = "";
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      
        try 
       {
            Class.forName("com.mysql.cj.jdbc.Driver");
                
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ams", "root", "Kirtan123@789");
            String query = "Delete from manageflights where flight_code ='"+flightCode+"'";
            Statement st = con.createStatement();
            int count = st.executeUpdate(query);
                
            JOptionPane.showMessageDialog(this, "Flight deleted!");   
            displayFlights();
       }
       catch(Exception e)
       {
            JOptionPane.showMessageDialog(this, e);
       }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void FlightsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsTableMouseClicked
        
        DefaultTableModel model = (DefaultTableModel)FlightsTable.getModel();
        int index = FlightsTable.getSelectedRow();
        //key = (model.getValueAt(index, 0).toString());
        flightCode = model.getValueAt(index, 0).toString();
        
        FSource.setSelectedItem((model.getValueAt(index, 2)).toString());
        FDestination.setSelectedItem((model.getValueAt(index, 3)).toString());    
        FCode.setText(model.getValueAt(index, 0).toString());
        NoOfSeats.setText(model.getValueAt(index, 1).toString());
        //date.setDate(model.getValueAt(index, 4).toString());
    }//GEN-LAST:event_FlightsTableMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/ams";
        String username = "root";
        String password = "Kirtan123@789";               
        
        String fcode = FCode.getText();
        int no_of_seats = Integer.valueOf(NoOfSeats.getText());
        String fsource = FSource.getSelectedItem().toString();
        String fdestination = FDestination.getSelectedItem().toString();
        String take_off_date = date.getDate().toString();
        
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con = DriverManager.getConnection(url, username, password);
            
            String query = "update manageflights set flight_code=?, no_of_seats=?, flight_source=?, flight_destination=?, take_off_date=? where flight_code='"+fcode+"'";
            
            PreparedStatement edit = con.prepareStatement(query);
            
            edit.setString(1, fcode);
            edit.setInt(2, no_of_seats);
            edit.setString(3,fsource);
            edit.setString(4, fdestination);
            edit.setString(5, take_off_date);           
                          
            int count = edit.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Flight details updated");

            displayFlights();
            clear();
            con.close();
            edit.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
            
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FCode;
    private javax.swing.JComboBox<String> FDestination;
    private javax.swing.JComboBox<String> FSource;
    private javax.swing.JTable FlightsTable;
    private javax.swing.JTextField NoOfSeats;
    private javax.swing.JPanel TakeOffDate;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
